### PR TITLE
first step to make code python3 compatible

### PR DESCRIPTION
**Pull request by 3c2b2ff5**
Now tests run also successfully as well as caching from AD.

### CODE REVIEW

**Comment by 3c2b2ff5** [comment]
The tests with Python3 will fail because of the missing implementation of `python3-mox3` in the test files.

**Comment by jaqx0r** [comment]
The dependencies for travis get installed in either requirements.txt for
deps out of PyPI, or from Debian via the apt command in .travis.yml.  If I
change the mox import to python3-mox3 will it just work? :) I'll try it.

**Comment by 3c2b2ff5** [comment]
cool. Sorry for the delay, I went to bed.

**Comment by 3c2b2ff5** [comment]
to get the test working we need to implement mox3 three in the test files as well. But I would rather to create a new branch `nsscache3` for instance, which will Python 3 only, that means you can revert my last pull request and keep `nsscache` Python 2 only and we go for Python 3 only in the new branch, since there will be no reason to have Python 3 compatibility in the Python 2 `nsscache` branch.
I have some time these days, so I'll create a Python 3 branch only and remove all Python 2 code from it as far as I can.
Or what do you have another suggestion?

**Comment by jaqx0r** [comment]
Sounds great! I'll follow your instructions.

**Comment by jaqx0r** [comment]
After a bit more thought let's not make another branch. If there's a need
to keep a python 2 version around, we can branch from before your merge.

**Comment by 3c2b2ff5** [comment]
OK. as you wish. I just created a [new branch](https://github.com/3c2b2ff5/nsscache/tree/python3_second), the code run successfully with Python 3, even the verify, only the tests are not quite successful. I think I need some help here.
These changes are only test wise to see how this can be approached.
I am sure you have much better ideas how to do it.
From here we can make a plan how take it a part and achieve the goal.

**Comment by 3c2b2ff5** [comment]
I wouldn't do a pull request, since this code wouldn't run under Python 2. Please clone it and let me know how things can be done better.

**Comment by 3c2b2ff5** [comment]
Successful was only AD. Unfortunately I cannot test the other sources.

**Comment by jaqx0r** [comment]
I'd like to be able to have the CI system spin up an openldap server and
run some integration tests, I've been dreaming of it for a long time now.
Seems like a good way to help you test now.

You're using samba4, right? We should be able to add that as an integration
test as well.

**Comment by 3c2b2ff5** [comment]
Yes I am using samba4. I could try. The installation and provisioning an Active Directory can be done with a script. I need to add few users and groups afterword. But it should be done with a script as well.
Do I need to consider some thing else beside do it with travis?

**Comment by jaqx0r** [comment]
No, if you can make a shell script that does the setup and test that would
be perfect!

**Comment by 3c2b2ff5** [comment]
OK. Where should I put the script?

**Comment by jaqx0r** [comment]
Please make a new top level directory 'tests'.

**Comment by 3c2b2ff5** [comment]
I pushed to [python3_second](https://github.com/3c2b2ff5/nsscache/tree/python3_second). I removed Python 2 from Dockerfile and setup.cfg and .travis.yml. It is not compatible anyway.
Few things in the script might not be needed, we will se how it behave and act accordingly.
Did you take a look at the modification I made regarding Python 3?

**Comment by 3c2b2ff5** [comment]
I just can't get further with the tests that fails in [Python3_second](https://github.com/3c2b2ff5/nsscache/tree/python3_second) branch. Would you please take a look?
As I said it is Python 3 only, that is why no pull request.

**Pull request merged**
