### PR TITLE
Fix error about getting user info exception while build index file

### PR DESCRIPTION
**Pull request by Hexiaoqiao**
Nsscache divides double steps when update local simple map files like passwd/group.
a. update cache files first,
b. build an index for this cache files.
In step b, it writes to target index file directly now. But it may return exception when invoke system call like #getpwnam_r, during building index. exception shows as following

> getpwnam_r: No such file or directory

The root cause is that 
a. Build index file is long operation especially there are huge user/group items.
b. When index for cache files does not build and persist completely, request may fail during building time since some user/group index may not find then throw exception.
I think we can quick fix it through writing index to tmp file then rename to target when persist completely (as PR shows). Another graceful solution I think is write cache file and index all to tmp first then rename to target may be more security. FYI.

### CODE REVIEW

**Comment by Hexiaoqiao** [comment]
I signed it!

**Comment by jaqx0r** [comment]
Thanks! Do you think you can write a test for the bug?

**Comment by Hexiaoqiao** [comment]
@jaqx0r update the PR and add new UT, I am not sure if the exception of CI is related to my PR, please double check if convenient.

**Comment by Hexiaoqiao** [comment]
Ping @jaqx0r,  Any more suggestions to push this forward?  We gray release this patch to production env, then never meet exceptions when invoke #getpwnam_r.  FYI.

**Comment by jaqx0r** [comment]
Thanks!

**Pull request merged**
