### PR TITLE
Fix reading rfc2307bis from conf file

### PR DESCRIPTION
**Pull request by kev009**
There is some chatter about this in the groups and issues, it didn't work for me until fixing the conditional.

### CODE REVIEW

**Comment by kev009** [comment]
Doc note, you need to use 'ldap_rfc2307bis in the conf file.

**Comment by jaqx0r** [comment]
Can you modify the example config and the nsscache.conf.5 manpage as well to describe this?  I never used this feature in anger so I'd appreciate someone who understands it to write the documentation, please.

**Comment by kev009** [comment]
Done

**Comment by jaqx0r** [comment]
Thanks!

**Pull request merged**
